#ifndef __GPIO_MAP_H
#define __GPIO_MAP_H

#define ADC_MESS_USB		(GPIOA), (GPIO_Pin_0)
#define ADC_MESS_UIN1		(GPIOA), (GPIO_Pin_1)
#define ADC_MESS_UIN2		(GPIOA), (GPIO_Pin_2)
#define ADC_MESS_UMLICHT	(GPIOA), (GPIO_Pin_3)
#define DAC_FLASHBRIGHT1	(GPIOA), (GPIO_Pin_4)
#define DAC_FLASHBRIGHT2	(GPIOA), (GPIO_Pin_5)
#define ADC_U_AKKU  		(GPIOA), (GPIO_Pin_6)
#define ADC_I_AKKU			(GPIOA), (GPIO_Pin_7)
#define DIN_nRTC_INT		(GPIOA), (GPIO_Pin_8)
#define RS232_TX			(GPIOA), (GPIO_Pin_9)
#define RS232_RX			(GPIOA), (GPIO_Pin_10)
#define DOUT_SENS_LOW		(GPIOA), (GPIO_Pin_11)
#define DOUT_DISP_ON		(GPIOA), (GPIO_Pin_12)
#define DIO_NRSTCAM			(GPIOA), (GPIO_Pin_15)

#define ADC_BQ_I			(GPIOB), (GPIO_Pin_0)
#define ADC_HW_VERSION		(GPIOB), (GPIO_Pin_1)
#define DIO_IMX6_STM1		(GPIOB), (GPIO_Pin_3)		// used for events recognized by STM
#define DIO_IMX6_STM2		(GPIOB), (GPIO_Pin_4)		// used for undervoltage indication
#define DIN_PIC_PWRON		(GPIOB), (GPIO_Pin_5)
#define I2C_SCL				(GPIOB), (GPIO_Pin_6)
#define I2C_SDA				(GPIOB), (GPIO_Pin_7)
#define PWM_PIEZO			(GPIOB), (GPIO_Pin_8)
#define PWM_DISP			(GPIOB), (GPIO_Pin_9)
#define PWM_FLASHSW1		(GPIOB), (GPIO_Pin_10)
#define PWM_FLASHSW2		(GPIOB), (GPIO_Pin_11)
#define DIN_nSW_OC_DISP_TCH (GPIOB), (GPIO_Pin_12)
#define DIN_nUSB3751_INT	(GPIOB), (GPIO_Pin_13)
#define DIO_ERWPIN			(GPIOB), (GPIO_Pin_14)
#define DIN_IMX6_PWRGOOD	(GPIOB), (GPIO_Pin_15)

#define ADC_AKKU_VERSION	(GPIOC), (GPIO_Pin_0)
#define ADC_AKKUTEMP1		(GPIOC), (GPIO_Pin_1)
#define ADC_AKKUTEMP2		(GPIOC), (GPIO_Pin_2)
#define ADC_KUEHLTEMP		(GPIOC), (GPIO_Pin_3)
#define DIO_IMX6_STM3		(GPIOC), (GPIO_Pin_4)
#define DOUT_3V3_ON			(GPIOC), (GPIO_Pin_5)
#define PWM_LED3_BLAU		(GPIOC), (GPIO_Pin_6)
#define PWM_LED4_ROT		(GPIOC), (GPIO_Pin_7)
#define PWM_LED4_GRN		(GPIOC), (GPIO_Pin_8)
#define PWM_LED4_BLAU		(GPIOC), (GPIO_Pin_9)
#define DIN_nSW_OC_SENS		(GPIOC), (GPIO_Pin_10)
#define DIO_IMX6_STM4		(GPIOC), (GPIO_Pin_11)
#define DOUT_BT_ON			(GPIOC), (GPIO_Pin_12)

#define DIN_nSW_OC_NFC		(GPIOD), (GPIO_Pin_0)
#define DIN_nSW_OC_SD_MEMS	(GPIOD), (GPIO_Pin_1)
#define DOUT_WLAN_ON		(GPIOD), (GPIO_Pin_2)
#define DOUT_TOUCH_ON		(GPIOD), (GPIO_Pin_3)
#define DOUT_NFC_ON			(GPIOD), (GPIO_Pin_4)
#define DOUT_SD_ON			(GPIOD), (GPIO_Pin_5)
#define DOUT_MEMS_ON 		(GPIOD), (GPIO_Pin_6)
#define DOUT_CAM_ON			(GPIOD), (GPIO_Pin_7)
#define DIN_nSW_OC_FUNK		(GPIOD), (GPIO_Pin_8)
#define DOUT_SENS_HIGH		(GPIOD), (GPIO_Pin_9)
#define DIN_nSW_OC_IMX6		(GPIOD), (GPIO_Pin_10)
#define DOUT_5V_ON			(GPIOD), (GPIO_Pin_11)
#define PWM_LED2_GRN		(GPIOD), (GPIO_Pin_12)
#define PWM_LED2_BLAU		(GPIOD), (GPIO_Pin_13)
#define PWM_LED3_ROT		(GPIOD), (GPIO_Pin_14)
#define PWM_LED3_GRN		(GPIOD), (GPIO_Pin_15)

#define DIN_BQ_INT			(GPIOE), (GPIO_Pin_0)
#define DIN_PIC_KEY_OUT		(GPIOE), (GPIO_Pin_1)
#define DIN_nBQ_PGOOD		(GPIOE), (GPIO_Pin_2)
#define DIN_BQ_STAT			(GPIOE), (GPIO_Pin_3)
#define DOUT_nBQ_CE			(GPIOE), (GPIO_Pin_4)
#define DOUT_BQ_PSEL		(GPIOE), (GPIO_Pin_5)
#define DIN_MAX_RS232_CONN	(GPIOE), (GPIO_Pin_6)
#define DOUT_WLEDS_ON		(GPIOE), (GPIO_Pin_7)
#define DIN_nSW_OC_WLED		(GPIOE), (GPIO_Pin_8)
#define PWM_LED1_ROT		(GPIOE), (GPIO_Pin_9)
#define DIO_TESTPIN1		(GPIOE), (GPIO_Pin_10)
#define PWM_LED1_GRN		(GPIOE), (GPIO_Pin_11)
#define DIN_nTEMP_PWROFF	(GPIOE), (GPIO_Pin_12)
#define PWM_LED1_BLAU		(GPIOE), (GPIO_Pin_13)
#define PWM_LED2_ROT		(GPIOE), (GPIO_Pin_14)
#define DIO_TESTPIN2		(GPIOE), (GPIO_Pin_15)

#endif
